name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json
        run: composer validate

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ matrix.php }}

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Run test suite
        run: composer test
